apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  namespace: $DEPLOY_NAMESPACE
  labels:
    project: $APP_NAME
    app: $APP_NAME
spec:
  selector:
    matchLabels:
      project: $APP_NAME
      app: $APP_NAME
  replicas: 1
  template:
    metadata:
      labels:
        project: $APP_NAME
        app: $APP_NAME
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: $APP_NAME
        image: $REGISTRY/$HARBOR_NAMESPACE/$APP_NAME:SNAPSHOT-$BUILD_NUMBER
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
            cpu: "400m"
          requests:
            memory: 100Mi
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
  namespace: $DEPLOY_NAMESPACE
  labels:
    project: $APP_NAME
    app: $APP_NAME
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: $NODE_PORT
  selector:
    project: $APP_NAME
    app: $APP_NAME
